name = "cpq-api"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
account_id = "34d894b7a693e5d10f6eb52820489854"  # Nav.sharma@codeium.com's Account

[vars]
REDIRECT_URI = "https://cpq-tool.pages.dev/auth/callback"
